# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5790ef4cb03591429076b49833db5763bc20c9f5c3aedc2d11c4f96059066c7ac9447e47fba452747a121c1bede1cd435c2af649c3781e3615a9003f04c7c0f

test:
  secret_key_base: 940d7f68cd7fb82e5a4ab7088c5f32065a878cde700a1ca69c7bec2ab02b9bbd5564ef8d46a61cd930e5cf9ba49fb8717ccbc09e1fbc6d20605687be161892a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
